// flow-typed signature: a83fd8f79fc101b57b5b2dd260010802
// flow-typed version: <<STUB>>/csv-string_v^3.1.6/flow_v0.105.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-string/lib/csv' {
  declare module.exports: any;
}

declare module 'csv-string/lib/parser' {
  declare module.exports: any;
}

declare module 'csv-string/lib/streamer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv-string/index' {
  declare module.exports: $Exports<'csv-string'>;
}
declare module 'csv-string/index.js' {
  declare module.exports: $Exports<'csv-string'>;
}
declare module 'csv-string/lib/csv.js' {
  declare module.exports: $Exports<'csv-string/lib/csv'>;
}
declare module 'csv-string/lib/parser.js' {
  declare module.exports: $Exports<'csv-string/lib/parser'>;
}
declare module 'csv-string/lib/streamer.js' {
  declare module.exports: $Exports<'csv-string/lib/streamer'>;
}
