// flow-typed signature: 191ed36eebfbb540cf58f6c258543d86
// flow-typed version: <<STUB>>/csv-string_v3.1.5/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "csv-string" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "csv-string/lib/csv" {
  declare module.exports: any;
}

declare module "csv-string/lib/parser" {
  declare module.exports: any;
}

declare module "csv-string/lib/streamer" {
  declare module.exports: any;
}

declare module "csv-string/t" {
  declare module.exports: any;
}

declare module "csv-string/x" {
  declare module.exports: any;
}

// Filename aliases
declare module "csv-string/index" {
  declare module.exports: $Exports<"csv-string">;
}
declare module "csv-string/index.js" {
  declare module.exports: $Exports<"csv-string">;
}
declare module "csv-string/lib/csv.js" {
  declare module.exports: $Exports<"csv-string/lib/csv">;
}
declare module "csv-string/lib/parser.js" {
  declare module.exports: $Exports<"csv-string/lib/parser">;
}
declare module "csv-string/lib/streamer.js" {
  declare module.exports: $Exports<"csv-string/lib/streamer">;
}
declare module "csv-string/t.js" {
  declare module.exports: $Exports<"csv-string/t">;
}
declare module "csv-string/x.js" {
  declare module.exports: $Exports<"csv-string/x">;
}
